# Generated by Django 3.2.9 on 2021-12-06 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Password', models.CharField(max_length=12)),
                ('IsActive', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'master',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fullname', models.CharField(max_length=30)),
                ('Mobile', models.CharField(max_length=10)),
                ('State', models.CharField(max_length=25)),
                ('City', models.CharField(max_length=25)),
                ('Address', models.CharField(max_length=150)),
                ('Master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todoapp.master')),
            ],
            options={
                'db_table': 'profile',
            },
        ),
    ]
